package manage;


import entityClasses.Employee;
import entityClasses.Project;
import importData.SystemData;
import javax.swing.JFrame;

import importData.ConnectionManager;
import entityClasses.ProjectPerson;

import javax.persistence.EntityManager;
import javax.persistence.Query;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

import javax.swing.table.DefaultTableModel;

public class ManageDevelopers extends javax.swing.JPanel {
    JFrame  panelHolder;
    SystemData systemData;
    
    List<Project> projectList;
    List<ProjectPerson> projectPersonList;
    List<Employee> empList;
    DefaultComboBoxModel model = new DefaultComboBoxModel();
    DefaultTableModel tableModel, tableModel1;
    int selectedProjectId;
    Employee selectedDeveloperToAdd;
    Employee selectedDeveloperToActivate;
        
    public ManageDevelopers(JFrame  panelHolder, SystemData systemData) {
        this.panelHolder = panelHolder;
        this.systemData = systemData;  
        initComponents();
        
        ConnectionManager cm = new ConnectionManager();
        EntityManager em = cm.getEntityManager();
        Query query = em.createQuery("Select p from Project p "
                + "where p.managerName= '" +systemData.getCurrentUser().getEmployee().getName()+"' "
                + " and p.status = 'In Progress'");              
        projectList = query.getResultList();
        for(Project project: projectList){
            model.addElement(project.getName()+" ("+project.getId()+")");
        }
        projectSelection.setModel(model);
        model.setSelectedItem(projectList.get(0).getName()+" ("+projectList.get(0).getId()+")");
        
        
        selectedProjectId = projectList.get(model.getIndexOf(model.getSelectedItem())).getId();
        query = em.createQuery("Select pp  from ProjectPerson pp "
                + "where pp.projectID= '" + selectedProjectId +"' and pp.personName != '"
                + systemData.getCurrentUser().getEmployee().getName() + "' ");
        projectPersonList = query.getResultList();        
        
        Object[] columnNames = {"Developer Name", "Title", "Bill Rate", "IsActivated"};
        Object[][] rowData = new Object[projectPersonList.size()][4];
        int i =0;       
        for(ProjectPerson projectPerson: projectPersonList){            
            Employee emp = em.find(Employee.class, projectPerson.getProjectPersonName().getName());
            rowData[i][0] = (Object) emp.getName();
            rowData[i][1] = (Object) emp.getTitle();
            rowData[i][2] = (Object) emp.getBillRate();
            rowData[i][3] = (Object) projectPerson.isIsActivated();
            ++i;
        };
        tableModel = new DefaultTableModel(rowData, columnNames);
        jTable1.setModel(tableModel);
        
        query = em.createQuery("Select emp from Employee emp where emp.EmpRole= 'Developer'"); 
        empList = query.getResultList();  
        for (ProjectPerson projectPerson : projectPersonList) {
            empList.remove(projectPerson.getProjectPersonName());
        }
        Object[] columnNames1 = {"Developer Name", "Title", "Bill Rate"};
        Object[][] rowData1 = new Object[empList.size()][3];
        
        
        i =0;       
        for(Employee emp: empList){            
            rowData1[i][0] = (Object) emp.getName();
            rowData1[i][1] = (Object) emp.getTitle();
            rowData1[i][2] = (Object) emp.getBillRate();
            ++i;
        };
        tableModel1 = new DefaultTableModel(rowData1, columnNames1);
        jTable2.setModel(tableModel1);
        
        cm.close();       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        activate = new javax.swing.JButton();
        dectivate = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        projectSelection = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        addButton = new javax.swing.JButton();

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        activate.setText("Activate");
        activate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                activateActionPerformed(evt);
            }
        });

        dectivate.setText("Deactivate");
        dectivate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dectivateActionPerformed(evt);
            }
        });

        jLabel1.setText("Existing Developers");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(dectivate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(activate)
                .addGap(20, 20, 20))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(activate)
                    .addComponent(dectivate))
                .addGap(6, 6, 6))
        );

        jLabel2.setText("Select a Project");

        projectSelection.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        projectSelection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                projectSelectionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(projectSelection, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 7, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(projectSelection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jLabel3.setText("Add Developer");

        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel3)
                .addGap(4, 4, 4)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addButton)
                .addGap(6, 6, 6))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(12, 12, 12))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void activateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_activateActionPerformed
        if(jTable1.getSelectedRow() == -1){
            JOptionPane.showMessageDialog(null, "Please select a Developer to Activate!");
            return;
        } 
        ProjectPerson selectedProjectPerson = projectPersonList.get(jTable1.getSelectedRow());
        
        if(selectedProjectPerson.isIsActivated().equals("Yes")){
            JOptionPane.showMessageDialog(null, "Developer is already Activated!");
            return;
        }
        ConnectionManager cm = new ConnectionManager();
        EntityManager em = cm.getEntityManager();
        ProjectPerson pp = em.find(ProjectPerson.class, selectedProjectPerson.getId());
        pp.setIsActivated("Yes");  
        cm.close();     
        projectPersonList.get(jTable1.getSelectedRow()).setIsActivated("Yes");
        tableModel.setValueAt("Yes", jTable1.getSelectedRow(), 3);   
    }//GEN-LAST:event_activateActionPerformed

    private void projectSelectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_projectSelectionActionPerformed
        ConnectionManager cm = new ConnectionManager();
        EntityManager em = cm.getEntityManager();
        
        selectedProjectId = projectList.get(model.getIndexOf(model.getSelectedItem())).getId();
        Query query = em.createQuery("Select pp  from ProjectPerson pp "
                + "where pp.projectID= '" + selectedProjectId +"' and pp.personName != '"
                + systemData.getCurrentUser().getEmployee().getName() + "' ");
        projectPersonList = query.getResultList();        
        
        Object[] columnNames = {"Developer Name", "Title", "Bill Rate", "IsActivated"};
        Object[][] rowData = new Object[projectPersonList.size()][4];
        int i =0;       
        for(ProjectPerson projectPerson: projectPersonList){            
            Employee emp = em.find(Employee.class, projectPerson.getProjectPersonName().getName());
            rowData[i][0] = (Object) emp.getName();
            rowData[i][1] = (Object) emp.getTitle();
            rowData[i][2] = (Object) emp.getBillRate();
            rowData[i][3] = (Object) projectPerson.isIsActivated();
            ++i;
        };
        jLabel1.setText("Existing Developers in: "+ projectSelection.getSelectedItem());
        tableModel = new DefaultTableModel(rowData, columnNames);
        jTable1.setModel(tableModel);
        
        query = em.createQuery("Select emp from Employee emp where emp.EmpRole= 'Developer'"); 
        List<Employee> empList = query.getResultList();  
        for (ProjectPerson projectPerson : projectPersonList) {
            empList.remove(projectPerson.getProjectPersonName());
        }
        Object[] columnNames1 = {"Developer Name", "Title", "Bill Rate"};
        Object[][] rowData1 = new Object[empList.size()][3];
        
        
        i =0;       
        for(Employee emp: empList){            
            rowData1[i][0] = (Object) emp.getName();
            rowData1[i][1] = (Object) emp.getTitle();
            rowData1[i][2] = (Object) emp.getBillRate();
            ++i;
        };
        jLabel3.setText("Add developers to: "+ projectSelection.getSelectedItem());
        tableModel1 = new DefaultTableModel(rowData1, columnNames1);
        jTable2.setModel(tableModel1);
        
        cm.close();         
    }//GEN-LAST:event_projectSelectionActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        if(jTable2.getSelectedRow() == -1){
            JOptionPane.showMessageDialog(null, "Please select a Developer to Add!");
            return;
        } 
        System.out.println(empList);
        System.out.println(jTable2.getSelectedRow());
        Employee selectedEmployee = empList.get(jTable2.getSelectedRow());   
        System.out.println(selectedEmployee);
                        
        ConnectionManager cm = new ConnectionManager();
        EntityManager em = cm.getEntityManager();
        ProjectPerson pp = new ProjectPerson(em.find(Project.class, selectedProjectId), selectedProjectId, selectedEmployee,
                selectedEmployee.getName(), "Yes", systemData.getCurrentUser().getEmployee().getName());
        em.persist(pp);
        
        Query query = em.createQuery("Select pp  from ProjectPerson pp "
                + "where pp.projectID= '" + selectedProjectId +"' and pp.personName != '"
                + systemData.getCurrentUser().getEmployee().getName() + "' ");
        projectPersonList = query.getResultList();        
        
        Object[] columnNames = {"Developer Name", "Title", "Bill Rate", "IsActivated"};
        Object[][] rowData = new Object[projectPersonList.size()][4];
        int i =0;       
        for(ProjectPerson projectPerson: projectPersonList){            
            Employee emp = em.find(Employee.class, projectPerson.getProjectPersonName().getName());
            rowData[i][0] = (Object) emp.getName();
            rowData[i][1] = (Object) emp.getTitle();
            rowData[i][2] = (Object) emp.getBillRate();
            rowData[i][3] = (Object) projectPerson.isIsActivated();
            ++i;
        };
        jLabel1.setText("Existing Developers in: "+ projectSelection.getSelectedItem());
        tableModel = new DefaultTableModel(rowData, columnNames);
        jTable1.setModel(tableModel);
        
        query = em.createQuery("Select emp from Employee emp where emp.EmpRole= 'Developer'"); 
        empList = query.getResultList();  
        for (ProjectPerson projectPerson : projectPersonList) {
            empList.remove(projectPerson.getProjectPersonName());
        }
        Object[] columnNames1 = {"Developer Name", "Title", "Bill Rate"};
        Object[][] rowData1 = new Object[empList.size()][3];        
        
        i =0;       
        for(Employee emp: empList){            
            rowData1[i][0] = (Object) emp.getName();
            rowData1[i][1] = (Object) emp.getTitle();
            rowData1[i][2] = (Object) emp.getBillRate();
            ++i;
        };
        jLabel3.setText("Add developers to: "+ projectSelection.getSelectedItem());
        tableModel1 = new DefaultTableModel(rowData1, columnNames1);
        jTable2.setModel(tableModel1);
        
        cm.close();
    }//GEN-LAST:event_addButtonActionPerformed

    private void dectivateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dectivateActionPerformed
        if(jTable1.getSelectedRow() == -1){
            JOptionPane.showMessageDialog(null, "Please select a Developer to Deactivate!");
            return;
        } 
        
        ProjectPerson selectedProjectPerson = projectPersonList.get(jTable1.getSelectedRow());        
        if(selectedProjectPerson.isIsActivated().equals("No")){
            JOptionPane.showMessageDialog(null, "Developer is already Deactivated!");
            return;
        }
        ConnectionManager cm = new ConnectionManager();
        EntityManager em = cm.getEntityManager();
        ProjectPerson pp = em.find(ProjectPerson.class, selectedProjectPerson.getId());
        pp.setIsActivated("No");  
        cm.close();                
        projectPersonList.get(jTable1.getSelectedRow()).setIsActivated("No");
        tableModel.setValueAt("No", jTable1.getSelectedRow(), 3);
    }//GEN-LAST:event_dectivateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton activate;
    private javax.swing.JButton addButton;
    private javax.swing.JButton dectivate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JComboBox<String> projectSelection;
    // End of variables declaration//GEN-END:variables
}
